In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
data = pd.read_table('fruit_data_with_colors_miss.txt')

In [3]:
data

    fruit_label fruit_name     fruit_subtype mass  width height  color_score
0             1      apple      granny_smith  192    8.4    7.3         0.55
1             1      apple      granny_smith  180    8.0    6.8         0.59
2             1      apple      granny_smith  176    7.4    7.2         0.60
3             2   mandarin          mandarin    ?    6.2    4.7         0.80
4             2   mandarin          mandarin  84     6.0    4.6         0.79
5             2   mandarin          mandarin  80     5.8    4.3         0.77
6             2   mandarin          mandarin  80     5.9    4.3         0.81
7             2   mandarin                 .   76    5.8    4.0         0.81
8             1      apple          braeburn  178    7.1      .         0.92
9             1      apple          braeburn  172    7.4    7.0         0.89
10            1      apple          braeburn  166    6.9    7.3         0.93
11            1      apple          braeburn  172    7.1    7.6         0.92
12            1      apple          braeburn  154    7.0    7.1         0.88
13            1      apple  golden_delicious  164    7.3    7.7         0.70
14            1      apple  golden_delicious  152    7.6    7.3         0.69
15            1      apple  golden_delicious  156    7.7    7.1         0.69
16            1      apple  golden_delicious  156    7.6    7.5         0.67
17            1      apple  golden_delicious  168    7.5    7.6         0.73
18            1      apple       cripps_pink  162    7.5    7.1         0.83
19            1      apple       cripps_pink  162    7.4    7.2         0.85
20            1      apple       cripps_pink  160    7.5    7.5         0.86
21            1      apple       cripps_pink  156    7.4    7.4         0.84
22            1      apple       cripps_pink  140    7.3    7.1         0.87
23            1      apple       cripps_pink  170    7.6    7.9         0.88
24            3     orange     spanish_jumbo  342    9.0    9.4         0.75
25            3     orange     spanish_jumbo  356    9.2    9.2         0.75
26            3     orange     spanish_jumbo  362    9.6    9.2         0.74
27            3     orange  selected_seconds  204    7.5    9.2         0.77
28            3     orange  selected_seconds  140    6.7    7.1         0.72
29            3     orange  selected_seconds  160    7.0    7.4         0.81
30            3     orange  selected_seconds  158    7.1    7.5         0.79
31            3     orange  selected_seconds  210    7.8    8.0         0.82
32            3     orange  selected_seconds  164    7.2    7.0         0.80
33            3     orange      turkey_navel  190    7.5    8.1         0.74
34            3     orange      turkey_navel  142    7.6    7.8         0.75
35            3     orange      turkey_navel  150    7.1    7.9         0.75
36            3     orange      turkey_navel  160    7.1    7.6         0.76
37            3     orange      turkey_navel  154    7.3    7.3         0.79
38            3     orange      turkey_navel  158    7.2    7.8         0.77
39            3     orange      turkey_navel  144    6.8    7.4         0.75
40            3     orange      turkey_navel  154    7.1    7.5         0.78
41            3     orange      turkey_navel  180    7.6    8.2         0.79
42            3     orange      turkey_navel  154    7.2    7.2         0.82
43            4      lemon    spanish_belsan  194    7.2   10.3         0.70
44            4      lemon    spanish_belsan  200    7.3   10.5         0.72
45            4      lemon    spanish_belsan  186    7.2    9.2         0.72
46            4      lemon    spanish_belsan  216    7.3   10.2         0.71
47            4      lemon    spanish_belsan  196    7.3    9.7         0.72
48            4      lemon    spanish_belsan  174    7.3   10.1         0.72
49            4      lemon           unknown  132    5.8    8.7         0.73
50            4      lemon           unknown  130    6.0    8.2         0.71
51            4      lemon           unknown  116    6.0    7.5         0.72
52            4      lemon           unknown  118    5.9    8.0         0.72
53            4      lemon           unknown  120    6.0    8.4         0.74
54            4      lemon           unknown  116    6.1    8.5         0.71
55            4      lemon           unknown  116    6.3    7.7         0.72
56            4      lemon           unknown  116    5.9    8.1         0.73
57            4      lemon           unknown  152    6.5    8.5         0.72
58            4      lemon           unknown  118    6.1    8.1         0.70

In [4]:
data = pd.read_table('fruit_data_with_colors_miss.txt',na_values=['.','?'])

In [5]:
data

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.0,8.4,7.3,0.55
1,1,apple,granny_smith,180.0,8.0,6.8,0.59
2,1,apple,granny_smith,176.0,7.4,7.2,0.60
3,2,mandarin,mandarin,NaN,6.2,4.7,0.80
4,2,mandarin,mandarin,84.0,6.0,4.6,0.79
5,2,mandarin,mandarin,80.0,5.8,4.3,0.77
6,2,mandarin,mandarin,80.0,5.9,4.3,0.81
7,2,mandarin,NaN,76.0,5.8,4.0,0.81
8,1,apple,braeburn,178.0,7.1,NaN,0.92
9,1,apple,braeburn,172.0,7.4,7.0,0.89
10,1,apple,braeburn,166.0,6.9,7.3,0.93
11,1,apple,braeburn,172.0,7.1,7.6,0.92
12,1,apple,braeburn,154.0,7.0,7.1,0.88
13,1,apple,golden_delicious,164.0,7.3,7.7,0.70
14,1,apple,golden_delicious,152.0,7.6,7.3,0.69
15,1,apple,golden_delicious,156.0,7.7,7.1,0.69
16,1,apple,golden_delicious,156.0,7.6,7.5,0.67
17,1,apple,golden_delicious,168.0,7.5,7.6,0.73
18,1,apple,cripps_pink,162.0,7.5,7.1,0.83
19,1,apple,cripps_pink,162.0,7.4,7.2,0.85
20,1,apple,cripps_pink,160.0,7.5,7.5,0.86
21,1,apple,cripps_pink,156.0,7.4,7.4,0.84
22,1,apple,cripps_pink,140.0,7.3,7.1,0.87
23,1,apple,cripps_pink,170.0,7.6,7.9,0.88
24,3,orange,spanish_jumbo,342.0,9.0,9.4,0.75
25,3,orange,spanish_jumbo,356.0,9.2,9.2,0.75
26,3,orange,spanish_jumbo,362.0,9.6,9.2,0.74
27,3,orange,selected_seconds,204.0,7.5,9.2,0.77
28,3,orange,selected_seconds,140.0,6.7,7.1,0.72
29,3,orange,selected_seconds,160.0,7.0,7.4,0.81
30,3,orange,selected_seconds,158.0,7.1,7.5,0.79
31,3,orange,selected_seconds,210.0,7.8,8.0,0.82
32,3,orange,selected_seconds,164.0,7.2,7.0,0.80
33,3,orange,turkey_navel,190.0,7.5,8.1,0.74
34,3,orange,turkey_navel,142.0,7.6,7.8,0.75
35,3,orange,turkey_navel,150.0,7.1,7.9,0.75
36,3,orange,turkey_navel,160.0,7.1,7.6,0.76
37,3,orange,turkey_navel,154.0,7.3,7.3,0.79
38,3,orange,turkey_navel,158.0,7.2,7.8,0.77
39,3,orange,turkey_navel,144.0,6.8,7.4,0.75
40,3,orange,turkey_navel,154.0,7.1,7.5,0.78
41,3,orange,turkey_navel,180.0,7.6,8.2,0.79
42,3,orange,turkey_navel,154.0,7.2,7.2,0.82
43,4,lemon,spanish_belsan,194.0,7.2,10.3,0.70
44,4,lemon,spanish_belsan,200.0,7.3,10.5,0.72
45,4,lemon,spanish_belsan,186.0,7.2,9.2,0.72
46,4,lemon,spanish_belsan,216.0,7.3,10.2,0.71
47,4,lemon,spanish_belsan,196.0,7.3,9.7,0.72
48,4,lemon,spanish_belsan,174.0,7.3,10.1,0.72
49,4,lemon,unknown,132.0,5.8,8.7,0.73
50,4,lemon,unknown,130.0,6.0,8.2,0.71
51,4,lemon,unknown,116.0,6.0,7.5,0.72
52,4,lemon,unknown,118.0,5.9,8.0,0.72
53,4,lemon,unknown,120.0,6.0,8.4,0.74
54,4,lemon,unknown,116.0,6.1,8.5,0.71
55,4,lemon,unknown,116.0,6.3,7.7,0.72
56,4,lemon,unknown,116.0,5.9,8.1,0.73
57,4,lemon,unknown,152.0,6.5,8.5,0.72
58,4,lemon,unknown,118.0,6.1,8.1,0.70

In [6]:
data.fillna(0)

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.0,8.4,7.3,0.55
1,1,apple,granny_smith,180.0,8.0,6.8,0.59
2,1,apple,granny_smith,176.0,7.4,7.2,0.60
3,2,mandarin,mandarin,0.0,6.2,4.7,0.80
4,2,mandarin,mandarin,84.0,6.0,4.6,0.79
5,2,mandarin,mandarin,80.0,5.8,4.3,0.77
6,2,mandarin,mandarin,80.0,5.9,4.3,0.81
7,2,mandarin,0,76.0,5.8,4.0,0.81
8,1,apple,braeburn,178.0,7.1,0.0,0.92
9,1,apple,braeburn,172.0,7.4,7.0,0.89
10,1,apple,braeburn,166.0,6.9,7.3,0.93
11,1,apple,braeburn,172.0,7.1,7.6,0.92
12,1,apple,braeburn,154.0,7.0,7.1,0.88
13,1,apple,golden_delicious,164.0,7.3,7.7,0.70
14,1,apple,golden_delicious,152.0,7.6,7.3,0.69
15,1,apple,golden_delicious,156.0,7.7,7.1,0.69
16,1,apple,golden_delicious,156.0,7.6,7.5,0.67
17,1,apple,golden_delicious,168.0,7.5,7.6,0.73
18,1,apple,cripps_pink,162.0,7.5,7.1,0.83
19,1,apple,cripps_pink,162.0,7.4,7.2,0.85
20,1,apple,cripps_pink,160.0,7.5,7.5,0.86
21,1,apple,cripps_pink,156.0,7.4,7.4,0.84
22,1,apple,cripps_pink,140.0,7.3,7.1,0.87
23,1,apple,cripps_pink,170.0,7.6,7.9,0.88
24,3,orange,spanish_jumbo,342.0,9.0,9.4,0.75
25,3,orange,spanish_jumbo,356.0,9.2,9.2,0.75
26,3,orange,spanish_jumbo,362.0,9.6,9.2,0.74
27,3,orange,selected_seconds,204.0,7.5,9.2,0.77
28,3,orange,selected_seconds,140.0,6.7,7.1,0.72
29,3,orange,selected_seconds,160.0,7.0,7.4,0.81
30,3,orange,selected_seconds,158.0,7.1,7.5,0.79
31,3,orange,selected_seconds,210.0,7.8,8.0,0.82
32,3,orange,selected_seconds,164.0,7.2,7.0,0.80
33,3,orange,turkey_navel,190.0,7.5,8.1,0.74
34,3,orange,turkey_navel,142.0,7.6,7.8,0.75
35,3,orange,turkey_navel,150.0,7.1,7.9,0.75
36,3,orange,turkey_navel,160.0,7.1,7.6,0.76
37,3,orange,turkey_navel,154.0,7.3,7.3,0.79
38,3,orange,turkey_navel,158.0,7.2,7.8,0.77
39,3,orange,turkey_navel,144.0,6.8,7.4,0.75
40,3,orange,turkey_navel,154.0,7.1,7.5,0.78
41,3,orange,turkey_navel,180.0,7.6,8.2,0.79
42,3,orange,turkey_navel,154.0,7.2,7.2,0.82
43,4,lemon,spanish_belsan,194.0,7.2,10.3,0.70
44,4,lemon,spanish_belsan,200.0,7.3,10.5,0.72
45,4,lemon,spanish_belsan,186.0,7.2,9.2,0.72
46,4,lemon,spanish_belsan,216.0,7.3,10.2,0.71
47,4,lemon,spanish_belsan,196.0,7.3,9.7,0.72
48,4,lemon,spanish_belsan,174.0,7.3,10.1,0.72
49,4,lemon,unknown,132.0,5.8,8.7,0.73
50,4,lemon,unknown,130.0,6.0,8.2,0.71
51,4,lemon,unknown,116.0,6.0,7.5,0.72
52,4,lemon,unknown,118.0,5.9,8.0,0.72
53,4,lemon,unknown,120.0,6.0,8.4,0.74
54,4,lemon,unknown,116.0,6.1,8.5,0.71
55,4,lemon,unknown,116.0,6.3,7.7,0.72
56,4,lemon,unknown,116.0,5.9,8.1,0.73
57,4,lemon,unknown,152.0,6.5,8.5,0.72
58,4,lemon,unknown,118.0,6.1,8.1,0.70

In [7]:
data.describe()

       fruit_label        mass      width     height  color_score
count    59.000000   58.000000  59.000000  58.000000    59.000000
mean      2.542373  164.448276   7.105085   7.691379     0.762881
std       1.208048   54.534770   0.816938   1.372830     0.076857
min       1.000000   76.000000   5.800000   4.000000     0.550000
25%       1.000000  140.500000   6.600000   7.200000     0.720000
50%       3.000000  159.000000   7.200000   7.600000     0.750000
75%       4.000000  177.500000   7.500000   8.200000     0.810000
max       4.000000  362.000000   9.600000  10.500000     0.930000

In [8]:
data.fillna(data.mean())

C:\Users\saulo\AppData\Local\Temp/ipykernel_10880/3231489778.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.fillna(data.mean())

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.000000,8.4,7.300000,0.55
1,1,apple,granny_smith,180.000000,8.0,6.800000,0.59
2,1,apple,granny_smith,176.000000,7.4,7.200000,0.60
3,2,mandarin,mandarin,164.448276,6.2,4.700000,0.80
4,2,mandarin,mandarin,84.000000,6.0,4.600000,0.79
5,2,mandarin,mandarin,80.000000,5.8,4.300000,0.77
6,2,mandarin,mandarin,80.000000,5.9,4.300000,0.81
7,2,mandarin,NaN,76.000000,5.8,4.000000,0.81
8,1,apple,braeburn,178.000000,7.1,7.691379,0.92
9,1,apple,braeburn,172.000000,7.4,7.000000,0.89
10,1,apple,braeburn,166.000000,6.9,7.300000,0.93
11,1,apple,braeburn,172.000000,7.1,7.600000,0.92
12,1,apple,braeburn,154.000000,7.0,7.100000,0.88
13,1,apple,golden_delicious,164.000000,7.3,7.700000,0.70
14,1,apple,golden_delicious,152.000000,7.6,7.300000,0.69
15,1,apple,golden_delicious,156.000000,7.7,7.100000,0.69
16,1,apple,golden_delicious,156.000000,7.6,7.500000,0.67
17,1,apple,golden_delicious,168.000000,7.5,7.600000,0.73
18,1,apple,cripps_pink,162.000000,7.5,7.100000,0.83
19,1,apple,cripps_pink,162.000000,7.4,7.200000,0.85
20,1,apple,cripps_pink,160.000000,7.5,7.500000,0.86
21,1,apple,cripps_pink,156.000000,7.4,7.400000,0.84
22,1,apple,cripps_pink,140.000000,7.3,7.100000,0.87
23,1,apple,cripps_pink,170.000000,7.6,7.900000,0.88
24,3,orange,spanish_jumbo,342.000000,9.0,9.400000,0.75
25,3,orange,spanish_jumbo,356.000000,9.2,9.200000,0.75
26,3,orange,spanish_jumbo,362.000000,9.6,9.200000,0.74
27,3,orange,selected_seconds,204.000000,7.5,9.200000,0.77
28,3,orange,selected_seconds,140.000000,6.7,7.100000,0.72
29,3,orange,selected_seconds,160.000000,7.0,7.400000,0.81
30,3,orange,selected_seconds,158.000000,7.1,7.500000,0.79
31,3,orange,selected_seconds,210.000000,7.8,8.000000,0.82
32,3,orange,selected_seconds,164.000000,7.2,7.000000,0.80
33,3,orange,turkey_navel,190.000000,7.5,8.100000,0.74
34,3,orange,turkey_navel,142.000000,7.6,7.800000,0.75
35,3,orange,turkey_navel,150.000000,7.1,7.900000,0.75
36,3,orange,turkey_navel,160.000000,7.1,7.600000,0.76
37,3,orange,turkey_navel,154.000000,7.3,7.300000,0.79
38,3,orange,turkey_navel,158.000000,7.2,7.800000,0.77
39,3,orange,turkey_navel,144.000000,6.8,7.400000,0.75
40,3,orange,turkey_navel,154.000000,7.1,7.500000,0.78
41,3,orange,turkey_navel,180.000000,7.6,8.200000,0.79
42,3,orange,turkey_navel,154.000000,7.2,7.200000,0.82
43,4,lemon,spanish_belsan,194.000000,7.2,10.300000,0.70
44,4,lemon,spanish_belsan,200.000000,7.3,10.500000,0.72
45,4,lemon,spanish_belsan,186.000000,7.2,9.200000,0.72
46,4,lemon,spanish_belsan,216.000000,7.3,10.200000,0.71
47,4,lemon,spanish_belsan,196.000000,7.3,9.700000,0.72
48,4,lemon,spanish_belsan,174.000000,7.3,10.100000,0.72
49,4,lemon,unknown,132.000000,5.8,8.700000,0.73
50,4,lemon,unknown,130.000000,6.0,8.200000,0.71
51,4,lemon,unknown,116.000000,6.0,7.500000,0.72
52,4,lemon,unknown,118.000000,5.9,8.000000,0.72
53,4,lemon,unknown,120.000000,6.0,8.400000,0.74
54,4,lemon,unknown,116.000000,6.1,8.500000,0.71
55,4,lemon,unknown,116.000000,6.3,7.700000,0.72
56,4,lemon,unknown,116.000000,5.9,8.100000,0.73
57,4,lemon,unknown,152.000000,6.5,8.500000,0.72
58,4,lemon,unknown,118.000000,6.1,8.100000,0.70

In [9]:
data['fruit_subtype'].value_counts().argmax()

0

In [10]:
data = data.fillna(data.mean())

C:\Users\saulo\AppData\Local\Temp/ipykernel_10880/476127175.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.mean())

In [11]:
data

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.000000,8.4,7.300000,0.55
1,1,apple,granny_smith,180.000000,8.0,6.800000,0.59
2,1,apple,granny_smith,176.000000,7.4,7.200000,0.60
3,2,mandarin,mandarin,164.448276,6.2,4.700000,0.80
4,2,mandarin,mandarin,84.000000,6.0,4.600000,0.79
5,2,mandarin,mandarin,80.000000,5.8,4.300000,0.77
6,2,mandarin,mandarin,80.000000,5.9,4.300000,0.81
7,2,mandarin,NaN,76.000000,5.8,4.000000,0.81
8,1,apple,braeburn,178.000000,7.1,7.691379,0.92
9,1,apple,braeburn,172.000000,7.4,7.000000,0.89
10,1,apple,braeburn,166.000000,6.9,7.300000,0.93
11,1,apple,braeburn,172.000000,7.1,7.600000,0.92
12,1,apple,braeburn,154.000000,7.0,7.100000,0.88
13,1,apple,golden_delicious,164.000000,7.3,7.700000,0.70
14,1,apple,golden_delicious,152.000000,7.6,7.300000,0.69
15,1,apple,golden_delicious,156.000000,7.7,7.100000,0.69
16,1,apple,golden_delicious,156.000000,7.6,7.500000,0.67
17,1,apple,golden_delicious,168.000000,7.5,7.600000,0.73
18,1,apple,cripps_pink,162.000000,7.5,7.100000,0.83
19,1,apple,cripps_pink,162.000000,7.4,7.200000,0.85
20,1,apple,cripps_pink,160.000000,7.5,7.500000,0.86
21,1,apple,cripps_pink,156.000000,7.4,7.400000,0.84
22,1,apple,cripps_pink,140.000000,7.3,7.100000,0.87
23,1,apple,cripps_pink,170.000000,7.6,7.900000,0.88
24,3,orange,spanish_jumbo,342.000000,9.0,9.400000,0.75
25,3,orange,spanish_jumbo,356.000000,9.2,9.200000,0.75
26,3,orange,spanish_jumbo,362.000000,9.6,9.200000,0.74
27,3,orange,selected_seconds,204.000000,7.5,9.200000,0.77
28,3,orange,selected_seconds,140.000000,6.7,7.100000,0.72
29,3,orange,selected_seconds,160.000000,7.0,7.400000,0.81
30,3,orange,selected_seconds,158.000000,7.1,7.500000,0.79
31,3,orange,selected_seconds,210.000000,7.8,8.000000,0.82
32,3,orange,selected_seconds,164.000000,7.2,7.000000,0.80
33,3,orange,turkey_navel,190.000000,7.5,8.100000,0.74
34,3,orange,turkey_navel,142.000000,7.6,7.800000,0.75
35,3,orange,turkey_navel,150.000000,7.1,7.900000,0.75
36,3,orange,turkey_navel,160.000000,7.1,7.600000,0.76
37,3,orange,turkey_navel,154.000000,7.3,7.300000,0.79
38,3,orange,turkey_navel,158.000000,7.2,7.800000,0.77
39,3,orange,turkey_navel,144.000000,6.8,7.400000,0.75
40,3,orange,turkey_navel,154.000000,7.1,7.500000,0.78
41,3,orange,turkey_navel,180.000000,7.6,8.200000,0.79
42,3,orange,turkey_navel,154.000000,7.2,7.200000,0.82
43,4,lemon,spanish_belsan,194.000000,7.2,10.300000,0.70
44,4,lemon,spanish_belsan,200.000000,7.3,10.500000,0.72
45,4,lemon,spanish_belsan,186.000000,7.2,9.200000,0.72
46,4,lemon,spanish_belsan,216.000000,7.3,10.200000,0.71
47,4,lemon,spanish_belsan,196.000000,7.3,9.700000,0.72
48,4,lemon,spanish_belsan,174.000000,7.3,10.100000,0.72
49,4,lemon,unknown,132.000000,5.8,8.700000,0.73
50,4,lemon,unknown,130.000000,6.0,8.200000,0.71
51,4,lemon,unknown,116.000000,6.0,7.500000,0.72
52,4,lemon,unknown,118.000000,5.9,8.000000,0.72
53,4,lemon,unknown,120.000000,6.0,8.400000,0.74
54,4,lemon,unknown,116.000000,6.1,8.500000,0.71
55,4,lemon,unknown,116.000000,6.3,7.700000,0.72
56,4,lemon,unknown,116.000000,5.9,8.100000,0.73
57,4,lemon,unknown,152.000000,6.5,8.500000,0.72
58,4,lemon,unknown,118.000000,6.1,8.100000,0.70

In [12]:
data['fruit_subtype'] = data['fruit_subtype'].fillna(data['fruit_subtype'].value_counts().argmax())

In [13]:
data

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.000000,8.4,7.300000,0.55
1,1,apple,granny_smith,180.000000,8.0,6.800000,0.59
2,1,apple,granny_smith,176.000000,7.4,7.200000,0.60
3,2,mandarin,mandarin,164.448276,6.2,4.700000,0.80
4,2,mandarin,mandarin,84.000000,6.0,4.600000,0.79
5,2,mandarin,mandarin,80.000000,5.8,4.300000,0.77
6,2,mandarin,mandarin,80.000000,5.9,4.300000,0.81
7,2,mandarin,0,76.000000,5.8,4.000000,0.81
8,1,apple,braeburn,178.000000,7.1,7.691379,0.92
9,1,apple,braeburn,172.000000,7.4,7.000000,0.89
10,1,apple,braeburn,166.000000,6.9,7.300000,0.93
11,1,apple,braeburn,172.000000,7.1,7.600000,0.92
12,1,apple,braeburn,154.000000,7.0,7.100000,0.88
13,1,apple,golden_delicious,164.000000,7.3,7.700000,0.70
14,1,apple,golden_delicious,152.000000,7.6,7.300000,0.69
15,1,apple,golden_delicious,156.000000,7.7,7.100000,0.69
16,1,apple,golden_delicious,156.000000,7.6,7.500000,0.67
17,1,apple,golden_delicious,168.000000,7.5,7.600000,0.73
18,1,apple,cripps_pink,162.000000,7.5,7.100000,0.83
19,1,apple,cripps_pink,162.000000,7.4,7.200000,0.85
20,1,apple,cripps_pink,160.000000,7.5,7.500000,0.86
21,1,apple,cripps_pink,156.000000,7.4,7.400000,0.84
22,1,apple,cripps_pink,140.000000,7.3,7.100000,0.87
23,1,apple,cripps_pink,170.000000,7.6,7.900000,0.88
24,3,orange,spanish_jumbo,342.000000,9.0,9.400000,0.75
25,3,orange,spanish_jumbo,356.000000,9.2,9.200000,0.75
26,3,orange,spanish_jumbo,362.000000,9.6,9.200000,0.74
27,3,orange,selected_seconds,204.000000,7.5,9.200000,0.77
28,3,orange,selected_seconds,140.000000,6.7,7.100000,0.72
29,3,orange,selected_seconds,160.000000,7.0,7.400000,0.81
30,3,orange,selected_seconds,158.000000,7.1,7.500000,0.79
31,3,orange,selected_seconds,210.000000,7.8,8.000000,0.82
32,3,orange,selected_seconds,164.000000,7.2,7.000000,0.80
33,3,orange,turkey_navel,190.000000,7.5,8.100000,0.74
34,3,orange,turkey_navel,142.000000,7.6,7.800000,0.75
35,3,orange,turkey_navel,150.000000,7.1,7.900000,0.75
36,3,orange,turkey_navel,160.000000,7.1,7.600000,0.76
37,3,orange,turkey_navel,154.000000,7.3,7.300000,0.79
38,3,orange,turkey_navel,158.000000,7.2,7.800000,0.77
39,3,orange,turkey_navel,144.000000,6.8,7.400000,0.75
40,3,orange,turkey_navel,154.000000,7.1,7.500000,0.78
41,3,orange,turkey_navel,180.000000,7.6,8.200000,0.79
42,3,orange,turkey_navel,154.000000,7.2,7.200000,0.82
43,4,lemon,spanish_belsan,194.000000,7.2,10.300000,0.70
44,4,lemon,spanish_belsan,200.000000,7.3,10.500000,0.72
45,4,lemon,spanish_belsan,186.000000,7.2,9.200000,0.72
46,4,lemon,spanish_belsan,216.000000,7.3,10.200000,0.71
47,4,lemon,spanish_belsan,196.000000,7.3,9.700000,0.72
48,4,lemon,spanish_belsan,174.000000,7.3,10.100000,0.72
49,4,lemon,unknown,132.000000,5.8,8.700000,0.73
50,4,lemon,unknown,130.000000,6.0,8.200000,0.71
51,4,lemon,unknown,116.000000,6.0,7.500000,0.72
52,4,lemon,unknown,118.000000,5.9,8.000000,0.72
53,4,lemon,unknown,120.000000,6.0,8.400000,0.74
54,4,lemon,unknown,116.000000,6.1,8.500000,0.71
55,4,lemon,unknown,116.000000,6.3,7.700000,0.72
56,4,lemon,unknown,116.000000,5.9,8.100000,0.73
57,4,lemon,unknown,152.000000,6.5,8.500000,0.72
58,4,lemon,unknown,118.000000,6.1,8.100000,0.70

In [14]:
data = pd.read_table('fruit_data_with_colors_miss.txt',na_values=['.','?'])

In [15]:
data

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192.0,8.4,7.3,0.55
1,1,apple,granny_smith,180.0,8.0,6.8,0.59
2,1,apple,granny_smith,176.0,7.4,7.2,0.60
3,2,mandarin,mandarin,NaN,6.2,4.7,0.80
4,2,mandarin,mandarin,84.0,6.0,4.6,0.79
5,2,mandarin,mandarin,80.0,5.8,4.3,0.77
6,2,mandarin,mandarin,80.0,5.9,4.3,0.81
7,2,mandarin,NaN,76.0,5.8,4.0,0.81
8,1,apple,braeburn,178.0,7.1,NaN,0.92
9,1,apple,braeburn,172.0,7.4,7.0,0.89
10,1,apple,braeburn,166.0,6.9,7.3,0.93
11,1,apple,braeburn,172.0,7.1,7.6,0.92
12,1,apple,braeburn,154.0,7.0,7.1,0.88
13,1,apple,golden_delicious,164.0,7.3,7.7,0.70
14,1,apple,golden_delicious,152.0,7.6,7.3,0.69
15,1,apple,golden_delicious,156.0,7.7,7.1,0.69
16,1,apple,golden_delicious,156.0,7.6,7.5,0.67
17,1,apple,golden_delicious,168.0,7.5,7.6,0.73
18,1,apple,cripps_pink,162.0,7.5,7.1,0.83
19,1,apple,cripps_pink,162.0,7.4,7.2,0.85
20,1,apple,cripps_pink,160.0,7.5,7.5,0.86
21,1,apple,cripps_pink,156.0,7.4,7.4,0.84
22,1,apple,cripps_pink,140.0,7.3,7.1,0.87
23,1,apple,cripps_pink,170.0,7.6,7.9,0.88
24,3,orange,spanish_jumbo,342.0,9.0,9.4,0.75
25,3,orange,spanish_jumbo,356.0,9.2,9.2,0.75
26,3,orange,spanish_jumbo,362.0,9.6,9.2,0.74
27,3,orange,selected_seconds,204.0,7.5,9.2,0.77
28,3,orange,selected_seconds,140.0,6.7,7.1,0.72
29,3,orange,selected_seconds,160.0,7.0,7.4,0.81
30,3,orange,selected_seconds,158.0,7.1,7.5,0.79
31,3,orange,selected_seconds,210.0,7.8,8.0,0.82
32,3,orange,selected_seconds,164.0,7.2,7.0,0.80
33,3,orange,turkey_navel,190.0,7.5,8.1,0.74
34,3,orange,turkey_navel,142.0,7.6,7.8,0.75
35,3,orange,turkey_navel,150.0,7.1,7.9,0.75
36,3,orange,turkey_navel,160.0,7.1,7.6,0.76
37,3,orange,turkey_navel,154.0,7.3,7.3,0.79
38,3,orange,turkey_navel,158.0,7.2,7.8,0.77
39,3,orange,turkey_navel,144.0,6.8,7.4,0.75
40,3,orange,turkey_navel,154.0,7.1,7.5,0.78
41,3,orange,turkey_navel,180.0,7.6,8.2,0.79
42,3,orange,turkey_navel,154.0,7.2,7.2,0.82
43,4,lemon,spanish_belsan,194.0,7.2,10.3,0.70
44,4,lemon,spanish_belsan,200.0,7.3,10.5,0.72
45,4,lemon,spanish_belsan,186.0,7.2,9.2,0.72
46,4,lemon,spanish_belsan,216.0,7.3,10.2,0.71
47,4,lemon,spanish_belsan,196.0,7.3,9.7,0.72
48,4,lemon,spanish_belsan,174.0,7.3,10.1,0.72
49,4,lemon,unknown,132.0,5.8,8.7,0.73
50,4,lemon,unknown,130.0,6.0,8.2,0.71
51,4,lemon,unknown,116.0,6.0,7.5,0.72
52,4,lemon,unknown,118.0,5.9,8.0,0.72
53,4,lemon,unknown,120.0,6.0,8.4,0.74
54,4,lemon,unknown,116.0,6.1,8.5,0.71
55,4,lemon,unknown,116.0,6.3,7.7,0.72
56,4,lemon,unknown,116.0,5.9,8.1,0.73
57,4,lemon,unknown,152.0,6.5,8.5,0.72
58,4,lemon,unknown,118.0,6.1,8.1,0.70

In [16]:
data.shape[0]

59

In [17]:
data.isnull().sum()

fruit_label      0
fruit_name       0
fruit_subtype    1
mass             1
width            0
height           1
color_score      0
dtype: int64

In [18]:
data.isnull().sum()/data.shape[0] * 100

fruit_label      0.000000
fruit_name       0.000000
fruit_subtype    1.694915
mass             1.694915
width            0.000000
height           1.694915
color_score      0.000000
dtype: float64

In [19]:
data = data[['fruit_label','fruit_name','fruit_subtype','width','height','color_score']]

In [20]:
data

    fruit_label fruit_name     fruit_subtype  width  height  color_score
0             1      apple      granny_smith    8.4     7.3         0.55
1             1      apple      granny_smith    8.0     6.8         0.59
2             1      apple      granny_smith    7.4     7.2         0.60
3             2   mandarin          mandarin    6.2     4.7         0.80
4             2   mandarin          mandarin    6.0     4.6         0.79
5             2   mandarin          mandarin    5.8     4.3         0.77
6             2   mandarin          mandarin    5.9     4.3         0.81
7             2   mandarin               NaN    5.8     4.0         0.81
8             1      apple          braeburn    7.1     NaN         0.92
9             1      apple          braeburn    7.4     7.0         0.89
10            1      apple          braeburn    6.9     7.3         0.93
11            1      apple          braeburn    7.1     7.6         0.92
12            1      apple          braeburn    7.0     7.1         0.88
13            1      apple  golden_delicious    7.3     7.7         0.70
14            1      apple  golden_delicious    7.6     7.3         0.69
15            1      apple  golden_delicious    7.7     7.1         0.69
16            1      apple  golden_delicious    7.6     7.5         0.67
17            1      apple  golden_delicious    7.5     7.6         0.73
18            1      apple       cripps_pink    7.5     7.1         0.83
19            1      apple       cripps_pink    7.4     7.2         0.85
20            1      apple       cripps_pink    7.5     7.5         0.86
21            1      apple       cripps_pink    7.4     7.4         0.84
22            1      apple       cripps_pink    7.3     7.1         0.87
23            1      apple       cripps_pink    7.6     7.9         0.88
24            3     orange     spanish_jumbo    9.0     9.4         0.75
25            3     orange     spanish_jumbo    9.2     9.2         0.75
26            3     orange     spanish_jumbo    9.6     9.2         0.74
27            3     orange  selected_seconds    7.5     9.2         0.77
28            3     orange  selected_seconds    6.7     7.1         0.72
29            3     orange  selected_seconds    7.0     7.4         0.81
30            3     orange  selected_seconds    7.1     7.5         0.79
31            3     orange  selected_seconds    7.8     8.0         0.82
32            3     orange  selected_seconds    7.2     7.0         0.80
33            3     orange      turkey_navel    7.5     8.1         0.74
34            3     orange      turkey_navel    7.6     7.8         0.75
35            3     orange      turkey_navel    7.1     7.9         0.75
36            3     orange      turkey_navel    7.1     7.6         0.76
37            3     orange      turkey_navel    7.3     7.3         0.79
38            3     orange      turkey_navel    7.2     7.8         0.77
39            3     orange      turkey_navel    6.8     7.4         0.75
40            3     orange      turkey_navel    7.1     7.5         0.78
41            3     orange      turkey_navel    7.6     8.2         0.79
42            3     orange      turkey_navel    7.2     7.2         0.82
43            4      lemon    spanish_belsan    7.2    10.3         0.70
44            4      lemon    spanish_belsan    7.3    10.5         0.72
45            4      lemon    spanish_belsan    7.2     9.2         0.72
46            4      lemon    spanish_belsan    7.3    10.2         0.71
47            4      lemon    spanish_belsan    7.3     9.7         0.72
48            4      lemon    spanish_belsan    7.3    10.1         0.72
49            4      lemon           unknown    5.8     8.7         0.73
50            4      lemon           unknown    6.0     8.2         0.71
51            4      lemon           unknown    6.0     7.5         0.72
52            4      lemon           unknown    5.9     8.0         0.72
53            4      lemon           unknown    6.0     8.4         0.74
54            4      lemon           unknown    6.1     8.5         0.71
55            4      lemon           unknown    6.3     7.7         0.72
56            4      lemon           unknown    5.9     8.1         0.73
57            4      lemon           unknown    6.5     8.5         0.72
58            4      lemon           unknown    6.1     8.1         0.70

In [21]:
data = pd.read_table('fruit_data_with_colors_miss.txt',na_values=['.','?'])

In [22]:
data = data.fillna(data.mean())

C:\Users\saulo\AppData\Local\Temp/ipykernel_10880/476127175.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.mean())

In [23]:
data = data[['mass','width','height','color_score']]

In [24]:
data

          mass  width     height  color_score
0   192.000000    8.4   7.300000         0.55
1   180.000000    8.0   6.800000         0.59
2   176.000000    7.4   7.200000         0.60
3   164.448276    6.2   4.700000         0.80
4    84.000000    6.0   4.600000         0.79
5    80.000000    5.8   4.300000         0.77
6    80.000000    5.9   4.300000         0.81
7    76.000000    5.8   4.000000         0.81
8   178.000000    7.1   7.691379         0.92
9   172.000000    7.4   7.000000         0.89
10  166.000000    6.9   7.300000         0.93
11  172.000000    7.1   7.600000         0.92
12  154.000000    7.0   7.100000         0.88
13  164.000000    7.3   7.700000         0.70
14  152.000000    7.6   7.300000         0.69
15  156.000000    7.7   7.100000         0.69
16  156.000000    7.6   7.500000         0.67
17  168.000000    7.5   7.600000         0.73
18  162.000000    7.5   7.100000         0.83
19  162.000000    7.4   7.200000         0.85
20  160.000000    7.5   7.500000         0.86
21  156.000000    7.4   7.400000         0.84
22  140.000000    7.3   7.100000         0.87
23  170.000000    7.6   7.900000         0.88
24  342.000000    9.0   9.400000         0.75
25  356.000000    9.2   9.200000         0.75
26  362.000000    9.6   9.200000         0.74
27  204.000000    7.5   9.200000         0.77
28  140.000000    6.7   7.100000         0.72
29  160.000000    7.0   7.400000         0.81
30  158.000000    7.1   7.500000         0.79
31  210.000000    7.8   8.000000         0.82
32  164.000000    7.2   7.000000         0.80
33  190.000000    7.5   8.100000         0.74
34  142.000000    7.6   7.800000         0.75
35  150.000000    7.1   7.900000         0.75
36  160.000000    7.1   7.600000         0.76
37  154.000000    7.3   7.300000         0.79
38  158.000000    7.2   7.800000         0.77
39  144.000000    6.8   7.400000         0.75
40  154.000000    7.1   7.500000         0.78
41  180.000000    7.6   8.200000         0.79
42  154.000000    7.2   7.200000         0.82
43  194.000000    7.2  10.300000         0.70
44  200.000000    7.3  10.500000         0.72
45  186.000000    7.2   9.200000         0.72
46  216.000000    7.3  10.200000         0.71
47  196.000000    7.3   9.700000         0.72
48  174.000000    7.3  10.100000         0.72
49  132.000000    5.8   8.700000         0.73
50  130.000000    6.0   8.200000         0.71
51  116.000000    6.0   7.500000         0.72
52  118.000000    5.9   8.000000         0.72
53  120.000000    6.0   8.400000         0.74
54  116.000000    6.1   8.500000         0.71
55  116.000000    6.3   7.700000         0.72
56  116.000000    5.9   8.100000         0.73
57  152.000000    6.5   8.500000         0.72
58  118.000000    6.1   8.100000         0.70

In [25]:
data.describe()

             mass      width     height  color_score
count   59.000000  59.000000  59.000000    59.000000
mean   164.448276   7.105085   7.691379     0.762881
std     54.062599   0.816938   1.360943     0.076857
min     76.000000   5.800000   4.000000     0.550000
25%    141.000000   6.600000   7.200000     0.720000
50%    160.000000   7.200000   7.600000     0.750000
75%    177.000000   7.500000   8.200000     0.810000
max    362.000000   9.600000  10.500000     0.930000

In [26]:
#(valor - min) / (max-min)

In [27]:
(25 - 12) / (59-12)

0.2765957446808511

In [28]:
(59-12) / (59-12)

1.0

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
mm = MinMaxScaler()

In [31]:
mm.fit(data)

MinMaxScaler()

In [32]:
data_escala = mm.transform(data)

In [33]:
data_escala

array([[0.40559441, 0.68421053, 0.50769231, 0.        ],
       [0.36363636, 0.57894737, 0.43076923, 0.10526316],
       [0.34965035, 0.42105263, 0.49230769, 0.13157895],
       [0.30925971, 0.10526316, 0.10769231, 0.65789474],
       [0.02797203, 0.05263158, 0.09230769, 0.63157895],
       [0.01398601, 0.        , 0.04615385, 0.57894737],
       [0.01398601, 0.02631579, 0.04615385, 0.68421053],
       [0.        , 0.        , 0.        , 0.68421053],
       [0.35664336, 0.34210526, 0.56790451, 0.97368421],
       [0.33566434, 0.42105263, 0.46153846, 0.89473684],
       [0.31468531, 0.28947368, 0.50769231, 1.        ],
       [0.33566434, 0.34210526, 0.55384615, 0.97368421],
       [0.27272727, 0.31578947, 0.47692308, 0.86842105],
       [0.30769231, 0.39473684, 0.56923077, 0.39473684],
       [0.26573427, 0.47368421, 0.50769231, 0.36842105],
       [0.27972028, 0.5       , 0.47692308, 0.36842105],
       [0.27972028, 0.47368421, 0.53846154, 0.31578947],
       [0.32167832, 0.44736842, 0.55384615, 0.47368421],
       [0.3006993 , 0.44736842, 0.47692308, 0.73684211],
       [0.3006993 , 0.42105263, 0.49230769, 0.78947368],
       [0.29370629, 0.44736842, 0.53846154, 0.81578947],
       [0.27972028, 0.42105263, 0.52307692, 0.76315789],
       [0.22377622, 0.39473684, 0.47692308, 0.84210526],
       [0.32867133, 0.47368421, 0.6       , 0.86842105],
       [0.93006993, 0.84210526, 0.83076923, 0.52631579],
       [0.97902098, 0.89473684, 0.8       , 0.52631579],
       [1.        , 1.        , 0.8       , 0.5       ],
       [0.44755245, 0.44736842, 0.8       , 0.57894737],
       [0.22377622, 0.23684211, 0.47692308, 0.44736842],
       [0.29370629, 0.31578947, 0.52307692, 0.68421053],
       [0.28671329, 0.34210526, 0.53846154, 0.63157895],
       [0.46853147, 0.52631579, 0.61538462, 0.71052632],
       [0.30769231, 0.36842105, 0.46153846, 0.65789474],
       [0.3986014 , 0.44736842, 0.63076923, 0.5       ],
       [0.23076923, 0.47368421, 0.58461538, 0.52631579],
       [0.25874126, 0.34210526, 0.6       , 0.52631579],
       [0.29370629, 0.34210526, 0.55384615, 0.55263158],
       [0.27272727, 0.39473684, 0.50769231, 0.63157895],
       [0.28671329, 0.36842105, 0.58461538, 0.57894737],
       [0.23776224, 0.26315789, 0.52307692, 0.52631579],
       [0.27272727, 0.34210526, 0.53846154, 0.60526316],
       [0.36363636, 0.47368421, 0.64615385, 0.63157895],
       [0.27272727, 0.36842105, 0.49230769, 0.71052632],
       [0.41258741, 0.36842105, 0.96923077, 0.39473684],
       [0.43356643, 0.39473684, 1.        , 0.44736842],
       [0.38461538, 0.36842105, 0.8       , 0.44736842],
       [0.48951049, 0.39473684, 0.95384615, 0.42105263],
       [0.41958042, 0.39473684, 0.87692308, 0.44736842],
       [0.34265734, 0.39473684, 0.93846154, 0.44736842],
       [0.1958042 , 0.        , 0.72307692, 0.47368421],
       [0.18881119, 0.05263158, 0.64615385, 0.42105263],
       [0.13986014, 0.05263158, 0.53846154, 0.44736842],
       [0.14685315, 0.02631579, 0.61538462, 0.44736842],
       [0.15384615, 0.05263158, 0.67692308, 0.5       ],
       [0.13986014, 0.07894737, 0.69230769, 0.42105263],
       [0.13986014, 0.13157895, 0.56923077, 0.44736842],
       [0.13986014, 0.02631579, 0.63076923, 0.47368421],
       [0.26573427, 0.18421053, 0.69230769, 0.44736842],
       [0.14685315, 0.07894737, 0.63076923, 0.39473684]])

In [34]:
data = pd.read_table('fruit_data_with_colors_miss.txt',na_values=['.','?'])

In [35]:
data = data.fillna(data.mean())

C:\Users\saulo\AppData\Local\Temp/ipykernel_10880/476127175.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data = data.fillna(data.mean())

In [36]:
macas = data[data['fruit_name'] == 'apple']

In [37]:
macas.describe()

       fruit_label        mass      width     height  color_score
count         19.0   19.000000  19.000000  19.000000    19.000000
mean           1.0  165.052632   7.457895   7.336388     0.783684
std            0.0   11.969747   0.345311   0.282648     0.124196
min            1.0  140.000000   6.900000   6.800000     0.550000
25%            1.0  156.000000   7.300000   7.100000     0.690000
50%            1.0  164.000000   7.400000   7.300000     0.840000
75%            1.0  172.000000   7.600000   7.550000     0.880000
max            1.0  192.000000   8.400000   7.900000     0.930000

In [38]:
est = macas['mass'].describe()

In [39]:
macas[(macas['mass'] > est['mean'] + (est['std']) * 2)]

   fruit_label fruit_name fruit_subtype   mass  width  height  color_score
0            1      apple  granny_smith  192.0    8.4     7.3         0.55

In [40]:
macas[(macas['mass'] < est['mean'] - (est['std']) * 2)]

    fruit_label fruit_name fruit_subtype   mass  width  height  color_score
22            1      apple   cripps_pink  140.0    7.3     7.1         0.87

In [41]:
est['std']

11.969747440993464